[package]
name = "elgamal-rs"
version = "0.1.0"
authors = ["Olgierd \"Allgreed\" Kasprowicz <olixem@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.5"
num-bigint = { version = "0.2", features = ["rand"] }

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
test-case = "0.3.3"
