@startuml
title Start Container

actor User
boundary UI
participant Main
participant Cluster
database Postgres
database LDAP

activate UI
User -> UI:List containers
UI -> Main:List containers
activate Main
Main -> LDAP: List containers
activate LDAP
LDAP --> Main: Containers list
deactivate LDAP
Main --> UI: Containers list
deactivate Main
UI -> User: Containers  list

User -> UI: Start container
UI -> Main: Start container
activate Main
Main ->> Postgres: Save request
activate Postgres
Postgres -> Postgres:Save request
Main -> Cluster: Start container
activate Cluster
deactivate Postgres
Cluster ->]: Download container
|||
Cluster <--]: Recieve container
Cluster -> Cluster: Start container
Cluster --> Main: Container status
deactivate Cluster
Main -> LDAP: Save container
activate LDAP
LDAP -> LDAP: Save container
LDAP --> Main: Saving status
deactivate LDAP
Main --> UI: Container status
deactivate Main
UI --> User: Container status
@enduml
